spring:
 
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stockdb2
    username: root
    password: root
  jpa:
     hibernate.ddl-auto: update
     properties:
      hibernate:
       dilect: org.hibernate.dialect.MySQL8Dialect
